name: eiden
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - ca-certificates=2024.2.2=hbcca054_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - ipykernel=6.29.3=pyhd33586a_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.0.13=h7f8727e_0
  - packaging=24.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=py38h06a4308_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.8.18=h955ad1f_0
  - python_abi=3.8=2_cp38
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - typing_extensions=4.10.0=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - affine==2.4.0
    - anyio==4.3.0
    - appdirs==1.4.4
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - async-lru==2.0.4
    - attrs==23.2.0
    - babel==2.14.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - certifi==2024.2.2
    - cffi==1.16.0
    - charset-normalizer==3.3.2
    - click==8.1.7
    - click-plugins==1.1.1
    - cligj==0.7.2
    - comm==0.2.2
    - contourpy==1.1.1
    - cycler==0.12.1
    - debugpy==1.8.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - exceptiongroup==1.2.0
    - fastjsonschema==2.19.1
    - filelock==3.13.1
    - fonttools==4.49.0
    - fqdn==1.5.1
    - fsspec==2024.2.0
    - gitdb==4.0.11
    - gitpython==3.1.42
    - h11==0.14.0
    - httpcore==1.0.4
    - httpx==0.27.0
    - idna==3.6
    - importlib-metadata==7.0.2
    - importlib-resources==6.3.0
    - ipython==8.12.3
    - isoduration==20.11.0
    - jinja2==3.1.3
    - joblib==1.3.2
    - json5==0.9.22
    - jsonpointer==2.4
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.1
    - jupyter-core==5.7.2
    - jupyter-events==0.9.1
    - jupyter-lsp==2.2.4
    - jupyter-server==2.13.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.1.4
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.25.4
    - kiwisolver==1.4.5
    - lightning-utilities==0.10.1
    - markupsafe==2.1.5
    - matplotlib==3.7.5
    - mistune==3.0.2
    - mpmath==1.3.0
    - nbclient==0.10.0
    - nbconvert==7.16.2
    - nbformat==5.10.2
    - networkx==3.1
    - notebook-shim==0.2.4
    - numpy==1.24.4
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu12==8.9.2.26
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu12==2.19.3
    - nvidia-nvjitlink-cu12==12.4.99
    - nvidia-nvtx-cu12==12.1.105
    - opencv-python==4.9.0.80
    - overrides==7.7.0
    - pandas==2.0.3
    - pandocfilters==1.5.1
    - pillow==10.2.0
    - pkgutil-resolve-name==1.3.10
    - prometheus-client==0.20.0
    - prompt-toolkit==3.0.43
    - protobuf==4.25.3
    - psutil==5.9.8
    - pycparser==2.21
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - python-json-logger==2.0.7
    - pytz==2024.1
    - pyyaml==6.0.1
    - rasterio==1.3.9
    - referencing==0.33.0
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.18.0
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - send2trash==1.8.2
    - sentry-sdk==1.42.0
    - setproctitle==1.3.3
    - smmap==5.0.1
    - sniffio==1.3.1
    - snuggs==1.4.7
    - soupsieve==2.5
    - stack-data==0.6.3
    - sympy==1.12
    - terminado==0.18.1
    - threadpoolctl==3.3.0
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torch==2.2.1
    - torchaudio==2.2.1
    - torchmetrics==1.3.1
    - torchsampler==0.1.2
    - torchsummary==1.5.1
    - torchvision==0.17.1
    - tornado==6.4
    - tqdm==4.66.2
    - traitlets==5.14.2
    - triton==2.2.0
    - types-python-dateutil==2.8.19.20240311
    - tzdata==2024.1
    - uri-template==1.3.0
    - urllib3==2.2.1
    - wandb==0.16.4
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.7.0
    - zipp==3.18.0
prefix: /home/eiden/anaconda3/envs/eiden
